name: CI

on:
  pull_request:
  push:
      branches:
      - main

jobs:
  mix_test:
    name: mix test (OTP ${{matrix.otp}} | Elixir ${{matrix.elixir}})
    strategy:
      matrix:
        include:
          - otp: 21.3.8.16
            elixir: 1.7.4
          - otp: 21.3.8.16
            elixir: 1.8.2
          - otp: 21.3.8.16
            elixir: 1.9.4
          - otp: 21.3.8.16
            elixir: 1.10.4
          - otp: 23.0.2
            elixir: 1.10.4
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: erlef/setup-elixir@v1.6.0
      with:
        otp-version: ${{matrix.otp}}
        elixir-version: ${{matrix.elixir}}
    - name: Start Google Chrome
      run: google-chrome --headless --disable-gpu --remote-debugging-port=9222 &
    - name: Install Dependencies
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix deps.get
    - name: Run Tests
      run: mix test
    - name: Upload screenshots
      uses: actions/upload-artifact@v2
      with:
        name: screenshots ${{ matrix.elixir }} ${{ matrix.otp }}
        path: tmp/screenshots
        retention-days: 14
